### ISSUE TITLE
涉及到链接跳转的地方用./是否会好些？

### ISSUE THREAD

**Issue by F1uYu4n** [code-scan/GourdScan#1]
比如
config.php→./config.php
api.php→./api.php
这样？

**Comment by ghost** [comment]
为什么？
假如是在子目录的，http://127.0.0.1/my/config.php跳转到api.php
api.php访问的就是http://127.0.0.1/my/api.php
而./api.php访问的是http://127.0.0.1/api.php，路径就不对了

**Comment by F1uYu4n** [comment]
./api.php也是当前目录啊，我之前把所有文件放到localhost/GourdScan/里，然后有的地方访问index.php就是localhost/index.php而不是localhost/GourdScan/index.php了

在 2015年12月4日 上午2:48，donghouhe notifications@github.com写道：

**Comment by kiang70** [comment]
我就在这掉坑里了，项目放在子目录/pscan/里，死活不行，后来发现api.php跳到主目录了，改为./api.php完美运行。

**Comment by code-scan** [comment]
嗯 编写的时候没考虑到子目录的问题，下次更新修改
